FROM golang:1.24.4-alpine

WORKDIR /app

# Disable CGO for static linking with PostgreSQL
ENV CGO_ENABLED=0

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o evergiven

# Final stage
FROM alpine:latest

# Install runtime dependencies
RUN apk add --no-cache ca-certificates

WORKDIR /app

# Copy binary from previous stage
COPY --from=0 /app/evergiven .

EXPOSE 8080
CMD ["./evergiven"] 